name: wwf_apps
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  http: ^0.13.3
  # toast: ^0.1.5
  connectivity: ^3.0.6
  # progress_dialog: ^1.2.4
  simple_fontellico_progress_dialog: ^0.2.1
  shared_preferences: ^2.0.6
  email_validator: ^2.0.1
  intl: ^0.17.0
  file_picker: ^4.2.3
  permission_handler: ^10.2.0
  mask_text_input_formatter: ^2.0.0
  mime: ^1.0.1
  gson: ^0.1.6-dev
  device_info: ^2.0.3
  date_format: ^2.0.4
  google_maps_flutter: ^2.0.0
  geolocator: ^9.0.2
  firebase_core: ^1.10.0
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^9.9.0
  # fluttertoast: ^8.0.8
  new_version: ^0.2.0
  package_info_plus:
  firebase_core_platform_interface: 4.5.1
  get: ^4.6.5
  geocoding: ^2.0.5
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an archive section, like this:
  assets:
    - archive/images/

  fonts:
    - family: AppFont
      fonts:
        - asset: archive/fonts/varela_round.otf
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "archive/images/logo_wwf.png"
  adaptive_icon_background: "#2CC285"